# This file can be used to send requests to Rest API using the vscode extension 
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# This file can only be used in VSCode.



### New driver request 
GET http://localhost:3000/vts/new_driver/hello


### Registering a driver
POST http://localhost:3000/vts/new_driver/register
content-type: application/json

{
    "driverName": "XYZ",
    "phoneNumber": "53466565547",
    "password": "!@#$"
}


###  Forgot password
POST http://localhost:3000/vts/new_driver/forgotPassword
content-type: application/json

{
    "driverName": "XYZ",
    "phoneNumber": "53466565547",
    "password": "!@#$"
}


###  Login
POST http://localhost:3000/vts/new_driver/login
content-type: application/json

{
    "driverName": "XYZ",
    "phoneNumber": "53466565547",
    "password": "!@#$"
}


###  Logout
POST http://localhost:3000/vts/new_driver/logout
content-type: application/json

{
    "driverName": "XYZ",
    "phoneNumber": "53466565547",
    "password": "!@#$"
}


# All admin requests are currently failing
### Get all drivers
GET http://localhost:3000/vts/admin/allDrivers


### Get all requested drivers
GET http://localhost:3000/vts/admin/getRequestedDrivers


###  delete driver
DELETE http://localhost:3000/vts/admin/deleteDriver
content-type: application/json

{
    "driverName": "XYZ",
    "phoneNumber": "53466565547",
    "password": "!@#$"
}


### Verified driver
POST http://localhost:3000/vts/admin/DriverVerified
content-type: application/json

{
    "verifiedDriverList": [{"driverName": "XYZ", "phoneNumber": "53466565547", "password": "!@#$"}]
}