# This file can be used to send requests to Rest API using the vscode extension 
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# This file can only be used in VSCode.


// Verify Driver
GET http://localhost:3000/vts/new_driver/verify
Authorization: token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZU51bWJlciI6IjEyMzQ1Njc4OTAiLCJ0aW1lU3RhbXAiOjE1ODkxMTc1NzcxNzksImlhdCI6MTU4OTExNzU3NywiZXhwIjoxNTg5MTE3Njk3fQ.DbvmHUFo6kSCv2LsTnUbVg_HeWN4780EGDkyqZ50cUGyWcg6xxGEC8nsjdPayUcxcCkMRHp4ch8QSAjwkAYK8w

### New driver request 
GET http://localhost:3000/vts/new_driver/hello


### Registering a driver
POST http://localhost:3000/vts/new_driver/register
content-type: application/json

{
    "driverName": "Raj",
    "phoneNumber": "1234567890",
    "password": "myPass"
}


###  Forgot password
POST http://localhost:3000/vts/new_driver/forgotPassword
content-type: application/json

{
    "driverName": "Raj",
    "phoneNumber": "1234567890",
    "password": "myPass"
}


###  Login
POST http://localhost:3000/vts/new_driver/login
content-type: application/json

{
    "driverName": "Raj",
    "phoneNumber": "1234567890",
    "password": "myPass"
}


###  Logout
POST http://localhost:3000/vts/new_driver/logout
content-type: application/json

{
    "driverName": "Raj",
    "phoneNumber": "1234567890",
    "password": "myPass"
}


### Get all drivers
GET http://localhost:3000/vts/admin/allDrivers


### Get all requested drivers
GET http://localhost:3000/vts/admin/getRequestedDrivers


###  delete driver
DELETE http://localhost:3000/vts/admin/deleteDriver
content-type: application/json

{
    "driverName": "Raj",
    "phoneNumber": "1234567890",
    "password": "myPass"
}

### Reject new driver
DELETE http://localhost:3000/vts/admin/rejectDriver
content-type: application/json

{
    "driverName": "Raj",
    "phoneNumber": "1234567890",
    "password": "myPass"
}

### Verified driver
POST http://localhost:3000/vts/admin/DriverVerified
content-type: application/json

{
    "verifiedDriverList": [{"driverName": "Raj", "phoneNumber": "1234567890", "password": "myPass"}]
}

### Verified all drivers
POST http://localhost:3000/vts/admin/DriverVerified
content-type: application/json

{
    "verifiedDriverList": [{"driverName": "Raj", "phoneNumber": "1234567890", "password": "myPass"},
    {"driverName": "ABC", "phoneNumber": "1234567890", "password": "myPass!!!"}]
}