# This file can be used to send requests to Rest API using the vscode extension 
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# This file can only be used in VSCode.



### New driver request 
GET http://localhost:3000/vts/new_driver/hello


### Registering a driver
POST http://localhost:3000/vts/new_driver/register
content-type: application/json

{
    "driverName": "XYZ",
    "phoneNumber": "1234567899",
    "password": "myPass2"
}


###  Forgot password
POST http://localhost:3000/vts/new_driver/forgotPassword
content-type: application/json

{
    "driverName": "XYZ",
    "phoneNumber": "1234567899",
    "password": "myPass2"
}


###  Login
POST http://localhost:3000/vts/new_driver/login
content-type: application/json

{
    "driverName": "XYZ",
    "phoneNumber": "1234567899",
    "password": "myPass2"
}


###  Logout
GET http://localhost:3000/vts/new_driver/logout
Authorization: token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZU51bWJlciI6IjEyMzQ1Njc4OTkiLCJ0aW1lU3RhbXAiOjE1OTIwNTQ0MjY4ODMsImlhdCI6MTU5MjA1NDQyNiwiZXhwIjoxNTkyMDY1MjI2fQ.P0CZhmTmKTcCywnW3oRqEwJbF1pc8G9HFZdhrk5IRUtufOWH-Iy9lHkPWRLc09jMuxvV6X1lqzUu8NRqB8QEyw

### Get all drivers
GET http://localhost:3000/vts/admin/allDrivers


### Get all requested drivers
GET http://localhost:3000/vts/admin/getRequestedDrivers


###  delete driver
DELETE http://localhost:3000/vts/admin/deleteDriver
content-type: application/json

{
    "driverName": "XYZ",
    "phoneNumber": "1234567899",
    "password": "myPass2"
}

### Reject new driver
DELETE http://localhost:3000/vts/admin/rejectDriver
content-type: application/json

{
    "driverName": "XYZ",
    "phoneNumber": "1234567899",
    "password": "myPass2"
}

### Verified driver
POST http://localhost:3000/vts/admin/DriverVerified
content-type: application/json

{
    "verifiedDriverList": [{"driverName": "XYZ", "phoneNumber": "1234567899", "password": "myPass2"}]
}

### Verified all drivers
POST http://localhost:3000/vts/admin/DriverVerified
content-type: application/json

{
    "verifiedDriverList": [{"driverName": "XYZ", "phoneNumber": "1234567899", "password": "myPass2"},
    {"driverName": "ABC", "phoneNumber": "1234567890", "password": "myPass!!!"}]
}